# janus-cert:
#   restart: always
#   image: apache
#   container_name: a-containers-manager
#   volumes_from:
#       - janus
#   volumes:
#     - "/root/janus/:/var/www/html"
#   environment:
#     - VIRTUAL_HOST=janus.yongbuzhixi.com
#     - LETSENCRYPT_HOST=janus.yongbuzhixi.com
#     - LETSENCRYPT_EMAIL=dale@yongbuzhixi.com
janus:
  build: .
  volumes:
    # - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "~/docker-nginx-https/config/nginx/certs:/root/janus/certs/"
  ports:
  - "7889:7889"
  - "7089:7089"
  - "8089:8089"
  - "7088:7088"
  - "8088:8088"
  - "8000:8000"
  - "8080:8080"
  - "10000-10200:10000-10200/udp"
  restart: always
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
